
s3:
  host: app.tinyest.org
  passkey: tat
  accessKey: kfje

db:
  host: app.tinyest.org
  port: 9042
  datacenter: datacenter1
  keyspace: chat2

queue:
  pulsar: 
    url: pulsar://localhost:6650

meili:
  host: https://meili.tinyest.org
  key: MASTER_KEY

quarkus:
  redis:
    devservices:
      enabled: false
  application:
    name: petit-chat
  live-reload:
    instrumentation: true
  http:
    port: 8090
    body: 
      delete-uploaded-files-on-end: true
    cors:
      ~: true
      access-control-max-age: 4H
      origins: []
    host: "0.0.0.0"
  oidc:
    auth-server-url: https://identity.tinyest.org/realms/concord
    client-id: concord-api
    credentials:
      secret: ClSs9qGPIOypvehwHTY0C6iYFdJ2K4RV
    token:
      principal-claim: sub

  